name: CI 

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Instalar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Construir con Maven
        run: mvn clean package -DskipTests
        
      - name: Guardar paquete generado para el trabajo de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: "${{ github.workspace }}/target/*.jar" 

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Instalar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Instalar Chrome y ChromeDriver
        uses: browser-actions/setup-chrome@v2
        with:
         
          chrome-version: 'latest'
          
          install-chromedriver: true
          
          install-dependencies: true
      
      - name: Ejecutar la aplicaci贸n para pruebas end to end
        run: mvn spring-boot:run & sleep 60

      - name: Ejecutar las pruebas unitarias, de integraci贸n y end to end
        run: mvn clean verify
  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2

      - name: Instalar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Construir con Maven
        run: mvn clean package -DskipTests

      - name: Revisar la calidad con Sonarqube
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin
  stage:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefacto del build
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java
      - name: Deploy to Azure Web App (Pre-Producci贸n)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-pre-hernandez'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_25AE17465ABC44659AA714B720622419 }}
          package: '*.jar'
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: qa
    if: github.ref=='refs/heads/master'
      
    steps:
      - name: Aprobaci贸n manual
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: KHGUAH
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-hernandez'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_662FBA3A06434B488CFB92F1A5AD0CB0 }}